BEGIN;

-- pgcrypto provides gen_random_uuid() which is used to generate run identifiers
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- Table: jobs
-- Description:
--   Stores job definitions (logical tasks) managed by the scheduler.
--   A job represents the configuration of a recurring or manual task.
--   Each job may produce multiple execution instances in job_instances.
-- ============================================================
CREATE TABLE IF NOT EXISTS jobs (

  -- Unique identifier of the job definition
  id BIGSERIAL PRIMARY KEY,

  -- Human readable job name (not necessarily unique)
  name VARCHAR(128) NOT NULL,

  -- Type of trigger mechanism
  -- cron   : scheduled execution using cron expression
  -- manual : triggered only via API/manual request
  trigger_type VARCHAR(16) NOT NULL DEFAULT 'cron',

  -- Cron expression defining execution schedule
  -- Required when trigger_type = 'cron'; for manual jobs it may be NULL/ignored
  cron_expr VARCHAR(64),

  -- Timezone used to evaluate cron schedule
  timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',

  -- Handler implementation type
  -- e.g. http, rpc, queue, script, worker-function
  handler_type VARCHAR(32) NOT NULL,

  -- Handler configuration payload
  -- Flexible JSON allowing handler-specific parameters
  handler_payload JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Maximum execution time allowed for a job instance
  timeout_sec INT NOT NULL DEFAULT 60,

  -- Maximum retry attempts after failure
  retry_limit INT NOT NULL DEFAULT 0,

  -- Delay between retries in seconds
  retry_backoff_sec INT NOT NULL DEFAULT 0,

  -- Retry backoff strategy
  -- fixed       : constant retry interval
  -- exponential : interval grows exponentially
  retry_backoff_strategy VARCHAR(16) NOT NULL DEFAULT 'fixed',

  -- Concurrency control policy when previous instance still running
  -- allow   : run concurrently
  -- forbid  : skip new execution
  -- replace : cancel previous instance and start new one
  concurrency_policy VARCHAR(16) NOT NULL DEFAULT 'allow',

  -- Behavior when scheduler misses execution time (misfire)
  -- skip     : ignore missed schedule
  -- fire_now : execute immediately
  -- catch_up : run all missed schedules
  misfire_policy VARCHAR(16) NOT NULL DEFAULT 'skip',

  -- Current job status
  -- active : scheduler will generate instances
  -- paused : scheduler will ignore job
  status VARCHAR(16) NOT NULL DEFAULT 'active',

  -- Next calculated execution time
  next_run_at TIMESTAMPTZ,

  -- Last time the scheduler created an instance
  last_scheduled_at TIMESTAMPTZ,

  -- Optimistic concurrency control version number
  version INT NOT NULL DEFAULT 1,

  -- Creation timestamp
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Last modification timestamp
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Soft delete timestamp
  deleted_at TIMESTAMPTZ,

  -- ------------------------------------------------------------
  -- Constraints
  -- ------------------------------------------------------------

  -- Validate trigger type
  CONSTRAINT chk_jobs_trigger_type
    CHECK (trigger_type IN ('cron', 'manual')),

  -- Validate job status
  CONSTRAINT chk_jobs_status
    CHECK (status IN ('active', 'paused')),

  -- Validate retry backoff strategy
  CONSTRAINT chk_jobs_retry_backoff_strategy
    CHECK (retry_backoff_strategy IN ('fixed', 'exponential')),

  -- Validate concurrency policy
  CONSTRAINT chk_jobs_concurrency_policy
    CHECK (concurrency_policy IN ('allow', 'forbid', 'replace')),

  -- Validate misfire policy
  CONSTRAINT chk_jobs_misfire_policy
    CHECK (misfire_policy IN ('skip', 'fire_now', 'catch_up')),

  -- Enforce cron_expr when using cron trigger
  CONSTRAINT chk_jobs_cron_expr_required CHECK (
    (trigger_type = 'cron' AND cron_expr IS NOT NULL) OR
    (trigger_type = 'manual')
  ),

  -- Ensure numeric fields are valid
  CONSTRAINT chk_jobs_non_negative CHECK (
    timeout_sec >= 1 AND
    retry_limit >= 0 AND
    retry_backoff_sec >= 0 AND
    version >= 1
  )
);

-- ============================================================
-- Table: job_instances
-- Description:
--   Stores execution records (instances) generated from jobs.
--   Each scheduled or manual execution corresponds to one row.
-- ============================================================
CREATE TABLE IF NOT EXISTS job_instances (

  -- Internal instance identifier
  id BIGSERIAL PRIMARY KEY,

  -- Unique execution run identifier
  -- Used for tracing, logging, and distributed execution
  run_id UUID NOT NULL DEFAULT gen_random_uuid(),

  -- Associated job definition
  job_id BIGINT NOT NULL REFERENCES jobs(id),

  -- Source of trigger
  -- schedule : generated by scheduler
  -- manual   : triggered via API
  -- retry    : retry attempt
  trigger_source VARCHAR(16) NOT NULL DEFAULT 'schedule',

  -- Scheduled execution time
  scheduled_at TIMESTAMPTZ NOT NULL,

  -- Current lifecycle state of instance
  status VARCHAR(16) NOT NULL DEFAULT 'pending',

  -- Routing key for worker sharding / queue partition
  routing_key VARCHAR(128),

  -- Worker node currently executing the task
  worker_id VARCHAR(64),

  -- Current retry attempt number
  attempt INT NOT NULL DEFAULT 1,

  -- Maximum attempts allowed
  max_attempt INT NOT NULL DEFAULT 1,

  -- Actual execution start time
  started_at TIMESTAMPTZ,

  -- Execution finish time
  finished_at TIMESTAMPTZ,

  -- Lease expiration time for distributed worker locking
  lease_expires_at TIMESTAMPTZ,

  -- Next retry time if execution failed
  retry_at TIMESTAMPTZ,

  -- Result classification code
  result_code VARCHAR(32),

  -- Failure error message or diagnostic info
  error_msg TEXT,

  -- Distributed trace identifier
  trace_id VARCHAR(64),

  -- Creation timestamp
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Last update timestamp
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- ------------------------------------------------------------
  -- Constraints
  -- ------------------------------------------------------------

  -- Validate trigger source
  CONSTRAINT chk_instances_trigger_source
    CHECK (trigger_source IN ('schedule', 'manual', 'retry')),

  -- Validate execution status state machine
  CONSTRAINT chk_instances_status CHECK (
    status IN (
      'pending',
      'dispatching',
      'running',
      'retry_wait',
      'success',
      'failed',
      'canceled'
    )
  ),

  -- Ensure retry counters are consistent
  CONSTRAINT chk_instances_attempt CHECK (
    attempt >= 1 AND
    max_attempt >= 1 AND
    attempt <= max_attempt
  )
);

-- ============================================================
-- Prevent duplicate scheduled executions
-- Ensures scheduler does not create duplicate instances
-- for the same job at the same scheduled time.
-- ============================================================
CREATE UNIQUE INDEX IF NOT EXISTS uniq_schedule_instance
ON job_instances(job_id, scheduled_at)
WHERE trigger_source = 'schedule';

-- Unique run identifier index
CREATE UNIQUE INDEX IF NOT EXISTS uniq_job_instances_run_id
ON job_instances(run_id);

-- ============================================================
-- Scheduler scanning index
-- Used to efficiently locate runnable jobs
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_jobs_active_next_run
ON jobs(status, next_run_at)
WHERE deleted_at IS NULL AND next_run_at IS NOT NULL;

-- ============================================================
-- Retry scanning index
-- Allows retry scanner/scheduler to find instances waiting for retry
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_instances_retry_scan
ON job_instances(status, retry_at);

-- ============================================================
-- Worker execution lookup index
-- Used for worker instance tracking
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_instances_worker_status
ON job_instances(worker_id, status);

-- ============================================================
-- Trigger Function: set_updated_at
-- Automatically updates updated_at on row modification
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach trigger to jobs table
DROP TRIGGER IF EXISTS trg_jobs_set_updated_at ON jobs;
CREATE TRIGGER trg_jobs_set_updated_at
BEFORE UPDATE ON jobs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Attach trigger to job_instances table
DROP TRIGGER IF EXISTS trg_job_instances_set_updated_at ON job_instances;
CREATE TRIGGER trg_job_instances_set_updated_at
BEFORE UPDATE ON job_instances
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
