#!/usr/bin/env bash
#
# Regenerates the load fixture's self-signed certificate.
#
# The fixture answers HTTPS on 8443 so the tls-handshake and tls-json-body
# probe something that actually speaks TLS. A public endpoint would make the
# load test depend on the internet and produce numbers nobody can reproduce, so
# the certificate is self-signed and the clients reach it with --insecure.
#
# The Secret it writes is a throwaway test credential. It is committed because
# the fixture has to start without a build step, and regenerating it is a
# deliberate act, not something that happens on every install.
#
# Usage: deploy/load/make-tls-cert.sh

set -euo pipefail

readonly HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly OUT="${HERE}/fixture-tls-secret.yaml"
readonly HOST="load-fixture.orbitjob-load.svc"
readonly DAYS=3650

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "$work/tls.key" -out "$work/tls.crt" \
    -days "$DAYS" -subj "/CN=${HOST}" \
    -addext "subjectAltName=DNS:${HOST},DNS:${HOST}.cluster.local,DNS:localhost" \
    2>/dev/null

# indent shifts every line by the given number of spaces.
indent() { sed "s/^/$(printf '%*s' "$1" '')/"; }

{
    printf '%s\n' \
        '# Generated by deploy/load/make-tls-cert.sh -- do not edit.' \
        '#' \
        '# A self-signed certificate for the load fixture. Clients reach it with' \
        '# --insecure, so nothing depends on the chain being trusted; it exists so' \
        '# the tls-handshake and tls-json-body families meet a real handshake.' \
        'apiVersion: v1' \
        'kind: Secret' \
        'metadata:' \
        '  name: load-fixture-tls' \
        '  namespace: orbitjob-load' \
        '  labels: {app: load-fixture}' \
        'type: kubernetes.io/tls' \
        'stringData:' \
        '  tls.crt: |'
    indent 4 <"$work/tls.crt"
    printf '%s\n' '  tls.key: |'
    indent 4 <"$work/tls.key"
} >"$OUT"

printf '[OK] wrote %s (valid %s days, CN=%s)\n' "$OUT" "$DAYS" "$HOST"
