package main

import (
	"bytes"
	"errors"
	"flag"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"

	adminhttp "orbitjob/internal/admin/http"
)

type exitPanic struct {
	code int
}

func TestMain_WriteAndCheckModes(t *testing.T) {
	outPath := filepath.Join(t.TempDir(), "openapi.yaml")

	runMainWithArgs(t, "-out", outPath)
	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read generated spec: %v", err)
	}
	if !bytes.HasSuffix(content, []byte("\n")) {
		t.Fatalf("expected generated file to end with newline")
	}

	runMainWithArgs(t, "-check", "-out", outPath)
}

func TestMain_RenderErrorExits(t *testing.T) {
	runMainExpectExit(t, 1, nil, func() {
		renderOpenAPIYAMLFn = func(adminhttp.OpenAPIDocument) ([]byte, error) {
			return nil, errors.New("boom")
		}
		main()
	})
}

func TestMain_CheckErrorExits(t *testing.T) {
	runMainExpectExit(t, 1, []string{"-check", "-out", "spec.yaml"}, func() {
		renderOpenAPIYAMLFn = func(adminhttp.OpenAPIDocument) ([]byte, error) {
			return []byte("openapi: 3.0.3\n"), nil
		}
		verifySpecFn = func(string, []byte) error {
			return errors.New("drift")
		}
		main()
	})
}

func TestMain_WriteErrorExits(t *testing.T) {
	runMainExpectExit(t, 1, []string{"-out", "spec.yaml"}, func() {
		renderOpenAPIYAMLFn = func(adminhttp.OpenAPIDocument) ([]byte, error) {
			return []byte("openapi: 3.0.3\n"), nil
		}
		writeSpecFn = func(string, []byte) error {
			return errors.New("write failed")
		}
		main()
	})
}

func TestRun_ParseError(t *testing.T) {
	err := run([]string{"-unknown-flag"})
	if err == nil {
		t.Fatalf("expected parse error")
	}
}

func TestRenderOpenAPIYAML(t *testing.T) {
	rendered, err := renderOpenAPIYAML(adminhttp.ServiceOpenAPIDocument())
	if err != nil {
		t.Fatalf("renderOpenAPIYAML: %v", err)
	}
	if !bytes.Contains(rendered, []byte("openapi: 3.0.3")) {
		t.Fatalf("expected yaml to contain openapi version, got:\n%s", string(rendered))
	}
	if !bytes.HasSuffix(rendered, []byte("\n")) {
		t.Fatalf("expected yaml output to end with newline")
	}
}

func TestRenderOpenAPIYAML_JSONMarshalError(t *testing.T) {
	doc := adminhttp.OpenAPIDocument{
		OpenAPI: "3.0.3",
		Paths:   map[string]adminhttp.PathItem{},
		Components: &adminhttp.OpenAPIComponents{
			Schemas: map[string]adminhttp.Schema{
				"Invalid": {
					Type:    "object",
					Default: math.Inf(1),
				},
			},
		},
	}

	_, err := renderOpenAPIYAML(doc)
	if err == nil || !strings.Contains(err.Error(), "marshal openapi json") {
		t.Fatalf("expected marshal error, got %v", err)
	}
}

func TestRenderOpenAPIYAML_JSONToYAMLError(t *testing.T) {
	old := jsonToYAML
	jsonToYAML = func([]byte) ([]byte, error) {
		return nil, errors.New("convert failed")
	}
	defer func() {
		jsonToYAML = old
	}()

	_, err := renderOpenAPIYAML(adminhttp.ServiceOpenAPIDocument())
	if err == nil || !strings.Contains(err.Error(), "convert json to yaml") {
		t.Fatalf("expected convert error, got %v", err)
	}
}

func TestRenderOpenAPIYAML_AppendsTrailingNewline(t *testing.T) {
	old := jsonToYAML
	jsonToYAML = func([]byte) ([]byte, error) {
		return []byte("openapi: 3.0.3"), nil
	}
	defer func() {
		jsonToYAML = old
	}()

	rendered, err := renderOpenAPIYAML(adminhttp.ServiceOpenAPIDocument())
	if err != nil {
		t.Fatalf("renderOpenAPIYAML: %v", err)
	}
	if !bytes.HasSuffix(rendered, []byte("\n")) {
		t.Fatalf("expected trailing newline to be appended, got %q", string(rendered))
	}
}

func TestVerifySpec(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "spec.yaml")
	generated := []byte("openapi: 3.0.3\n")

	if err := os.WriteFile(path, generated, 0o644); err != nil {
		t.Fatalf("write seed file: %v", err)
	}
	if err := verifySpec(path, generated); err != nil {
		t.Fatalf("verifySpec expected success, got %v", err)
	}

	err := verifySpec(path, []byte("openapi: 3.1.0\n"))
	if err == nil || !strings.Contains(err.Error(), "openapi spec drift detected") {
		t.Fatalf("expected drift error, got %v", err)
	}

	err = verifySpec(filepath.Join(tmpDir, "missing.yaml"), generated)
	if err == nil || !strings.Contains(err.Error(), "read") {
		t.Fatalf("expected read error for missing file, got %v", err)
	}
}

func TestWriteSpec(t *testing.T) {
	path := filepath.Join(t.TempDir(), "nested", "spec.yaml")
	generated := []byte("openapi: 3.0.3\n")

	if err := writeSpec(path, generated); err != nil {
		t.Fatalf("writeSpec: %v", err)
	}

	written, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read written spec: %v", err)
	}
	if !bytes.Equal(written, generated) {
		t.Fatalf("expected written spec to match generated bytes")
	}
}

func TestWriteSpec_WriteError(t *testing.T) {
	dir := t.TempDir()
	err := writeSpec(dir, []byte("openapi: 3.0.3\n"))
	if err == nil || !strings.Contains(err.Error(), "write") {
		t.Fatalf("expected write error when target path is directory, got %v", err)
	}
}

func TestWriteSpec_MkdirError(t *testing.T) {
	err := writeSpec(filepath.Join("bad\x00dir", "spec.yaml"), []byte("openapi: 3.0.3\n"))
	if err == nil || !strings.Contains(err.Error(), "mkdir") {
		t.Fatalf("expected mkdir error for invalid path, got %v", err)
	}
}

func runMainWithArgs(t *testing.T, args ...string) {
	t.Helper()

	oldArgs := os.Args
	oldCommandLine := flag.CommandLine

	os.Args = append([]string{"openapi-gen"}, args...)
	flag.CommandLine = flag.NewFlagSet(os.Args[0], flag.ContinueOnError)

	oldRender := renderOpenAPIYAMLFn
	oldVerify := verifySpecFn
	oldWrite := writeSpecFn
	oldExit := exitFn
	oldJSONToYAML := jsonToYAML

	defer func() {
		os.Args = oldArgs
		flag.CommandLine = oldCommandLine
		renderOpenAPIYAMLFn = oldRender
		verifySpecFn = oldVerify
		writeSpecFn = oldWrite
		exitFn = oldExit
		jsonToYAML = oldJSONToYAML
	}()

	main()
}

func runMainExpectExit(t *testing.T, wantCode int, args []string, run func()) {
	t.Helper()

	oldArgs := os.Args
	oldCommandLine := flag.CommandLine
	oldRender := renderOpenAPIYAMLFn
	oldVerify := verifySpecFn
	oldWrite := writeSpecFn
	oldExit := exitFn
	oldJSONToYAML := jsonToYAML

	os.Args = append([]string{"openapi-gen"}, args...)
	flag.CommandLine = flag.NewFlagSet(os.Args[0], flag.ContinueOnError)
	exitFn = func(code int) {
		panic(exitPanic{code: code})
	}

	defer func() {
		os.Args = oldArgs
		flag.CommandLine = oldCommandLine
		renderOpenAPIYAMLFn = oldRender
		verifySpecFn = oldVerify
		writeSpecFn = oldWrite
		exitFn = oldExit
		jsonToYAML = oldJSONToYAML
	}()

	defer func() {
		r := recover()
		if r == nil {
			t.Fatalf("expected main to exit with code %d", wantCode)
		}
		exit, ok := r.(exitPanic)
		if !ok {
			t.Fatalf("expected exit panic, got %T (%v)", r, r)
		}
		if exit.code != wantCode {
			t.Fatalf("expected exit code %d, got %d", wantCode, exit.code)
		}
	}()

	run()
}
